name: tooth_tales
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mailer: ^6.0.1
  url_launcher: ^6.0.20
  platform: ^3.1.0
  flutter_local_notifications: ^17.1.2
  permission_handler: ^11.3.1
  timezone: ^0.9.3
  google_generative_ai: ^0.4.3
  intl: ^0.17.0
  http: ^1.2.1
  camera: ^0.10.5+5
  font_awesome_flutter: ^10.8.0
#  flutter_dotenv: ^3.1.0

  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.6
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.0.1
  image_picker: ^1.1.2
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  timeago: ^3.3.0
  tflite_flutter: ^0.11.0
  path_provider: ^2.1.4
  image: ^3.3.0
  image_cropper: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter



  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Images/
    - assets/model/oralcancer_model.tflite
    - assets/model/mobilenet_model.tflite
    - assets/model/disease_model.tflite

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf

          style: italic

